apiVersion: apps/v1
kind: Deployment
metadata:
  name: aquacounter
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aquacounter
  template:
    metadata:
      labels:
        app: aquacounter
    spec:
      serviceAccountName: aquacounter-service-account  # Agrega esta línea
      containers:
      - name: aquacounter
        image: covadongafdez/aquacounter:2c4335eaf82b0c31c4642d6894824a096b63399e
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 500m
            memory: 500Mi
        envFrom:
        - secretRef:
            name: aquacounter-env
