apiVersion: v1
kind: ServiceAccount
metadata:
  name: aquacounter-service-account
  namespace: apps

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: apps
  name: secret-access-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-access-binding
  namespace: apps
subjects:
- kind: ServiceAccount
  name: aquacounter-service-account
  namespace: apps
roleRef:
  kind: Role
  name: secret-access-role
  apiGroup: rbac.authorization.k8s.io
