name: Build and Push Docker Image and Update K8s Manifest

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'  # Ignora los cambios en esta ruta para evitar que entre en bucle

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .  # Contexto de la construcción (directorio del proyecto)
        file: ./Dockerfile  # Ruta al Dockerfile
        push: true
        tags: covadongafdez/aquacounter:${{ github.sha }}  # Etiqueta de la imagen con el SHA del commit

    - name: Update Kubernetes manifest
      run: |
        sed -i 's|covadongafdez/aquacounter:.*|covadongafdez/aquacounter:${{ github.sha }}|g' ./k8s/deployment.yml
        cat ./k8s/deployment.yml
        git config user.name 'Covadonga Fernandez Benavente'
        git config user.email 'covadongafdez@outlook.com'
        git add .
        git commit -m "Update deployment manifest with new image tag"
        git push
