name: Build and Push Docker Image and Update K8s Manifest

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/deployment.yaml'  # Ignora cambios en este archivo para evitar bucles
    paths:
      - '**'  # Incluye todos los demás archivos y carpetas para la construcción

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Contexto de la construcción (directorio del proyecto)
        file: ./Dockerfile  # Ruta al Dockerfile
        push: true
        tags: yourusername/yourimagename:${{ github.sha }}  # Etiqueta de la imagen con el SHA del commit

    - name: Update Kubernetes manifest
      run: |
        sed -i 's|yourusername/yourimagename:.*|yourusername/yourimagename:${{ github.sha }}|g' ./k8s/deployment.yaml

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add ./k8s/deployment.yaml
        git commit -m "Update deployment manifest with new image tag"
        git push
